name: Build, Test and Publish

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Lint extension
        run: npm run lint
        
      - name: Run tests
        run: npm run test
        
      - name: Build extension
        run: npm run build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-build
          path: web-ext-artifacts/*.zip
          
  publish:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-build
          path: web-ext-artifacts
          
      - name: Sign and publish extension
        run: npm run sign
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: web-ext-artifacts/*.xpi